use crate::core::wallet::WalletNetwork;
use crate::infra::storage::WalletSortField;
use crate::ui::components::tag_picker::TagMessage;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ImportMode {
    Bip39,
    Slip39,
    Encrypted,
}

#[derive(Debug, Clone)]
pub enum WalletsMessage {
    ToggleCreateForm,
    CreateWallet,
    NameChanged(String),
    NetworkChanged(WalletNetwork),
    ToggleImportMnemonicForm,
    ImportModeChanged(ImportMode),
    ImportNameChanged(String),
    ImportNetworkChanged(WalletNetwork),
    ImportMnemonicChanged(String),
    ImportEncryptedPathChanged(String),
    ImportEncryptedPassphraseChanged(String),
    ImportSlip39PassphraseChanged(String),
    ImportSlip39ShareChanged(usize, String),
    BrowseImportEncryptedPath,
    AddImportSlip39Share,
    RemoveImportSlip39Share,
    ImportWalletFromMnemonic,
    ImportWalletFromSlip39,
    ImportWalletFromEncrypted,
    SelectWallet(usize),
    DeleteWallet(usize),
    ConfirmDelete(usize),
    CancelDelete,
    ShowBackupWarning(usize),
    MnemonicPassphraseChanged(String),
    RevealMnemonic(usize),
    ToggleBackupTest {
        wallet_index: usize,
        word_count: usize,
    },
    ExportMnemonicPdf(usize),
    ExportMnemonicEncrypted(usize),
    Slip39ExportThresholdChanged(String),
    Slip39ExportShareCountChanged(String),
    Slip39ExportPassphraseChanged(String),
    ExportSlip39Shares(usize),
    BackupWordChanged(usize, String),
    SubmitBackupTest(usize),
    DismissWalletNotice,
    ToggleExternalAddresses,
    ToggleInternalAddresses,
    CopyAddress(String),
    DeletePassphraseChanged(String),
    SortFieldChanged(WalletSortField),
    ToggleSortDirection,
    TagMessage(TagMessage),
    ToggleTagModal(usize),
}

pub enum WalletsEvent {
    CreateWallet(String, WalletNetwork),
    ImportWalletFromMnemonic {
        name: String,
        network: WalletNetwork,
        mnemonic: String,
    },
    ImportWalletFromSlip39 {
        name: String,
        network: WalletNetwork,
        shares: Vec<String>,
        slip39_passphrase: String,
    },
    BrowseImportEncryptedPath,
    ImportWalletFromEncrypted {
        path: String,
        passphrase: String,
        name_override: Option<String>,
    },
    SelectWallet(usize),
    DeleteWallet(usize),
    RevealMnemonic {
        wallet_index: usize,
        passphrase: String,
    },
    VerifyMnemonicBackup {
        wallet_index: usize,
        checks: Vec<(usize, String)>,
    },
    ExportMnemonicPdf(usize),
    ExportMnemonicEncrypted(usize),
    ExportWalletSlip39 {
        wallet_index: usize,
        threshold: u8,
        share_count: u8,
        slip39_passphrase: String,
    },
    CopyAddress(String),
    SortFieldChanged(WalletSortField),
    ToggleSortDirection,
    TagInputChanged(String),
    RemoveTag(String),
}

pub struct WalletsView {
    pub create_name: String,
    pub create_network: WalletNetwork,
    pub show_create_form: bool,
    pub import_mode: ImportMode,
    pub import_name: String,
    pub import_network: WalletNetwork,
    pub import_mnemonic: String,
    pub import_encrypted_path: String,
    pub import_encrypted_passphrase: String,
    pub import_slip39_passphrase: String,
    pub import_slip39_shares: Vec<String>,
    pub show_import_mnemonic_form: bool,
    pub confirm_delete_index: Option<usize>,
    pub delete_passphrase: String,
    pub notice_wallet_index: Option<usize>,
    pub mnemonic_passphrase: String,
    pub revealed_wallet_index: Option<usize>,
    pub backup_test_wallet_index: Option<usize>,
    pub backup_test_positions: Vec<usize>,
    pub backup_test_answers: Vec<String>,
    pub slip39_export_threshold: String,
    pub slip39_export_share_count: String,
    pub slip39_export_passphrase: String,
    pub show_external_addresses: bool,
    pub show_internal_addresses: bool,
    pub copied_address: Option<String>,
    pub info: Option<String>,
    pub error: Option<String>,
    /// Compact mode flag
    #[allow(dead_code)]
    pub compact_mode: bool,
    /// Sorting state
    pub sort_field: WalletSortField,
    pub sort_ascending: bool,
    /// Tag management state
    pub tag_input: String,
    pub tag_modal_index: Option<usize>,
}
